version: 0.2

phases:
  install:
    commands:
      - echo Installing Terraform...
      - curl -L -o terraform.zip https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform -version

  pre_build:
    commands:
      - terraform init
      - terraform validate

  build:
    commands:
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'
